import { drizzle } from "drizzle-orm/mysql2";
import { env } from "../api/lib/env";
import * as schema from "./schema";
import * as relations from "./relations";

const fullSchema = { ...schema, ...relations };
const db = drizzle(env.databaseUrl, { mode: "planetscale", schema: fullSchema });
import { networks, devices, deviceConnections, deviceConfigs, scanJobs } from "./schema";

async function seed() {

  // Create demo networks
  const [network1, network2] = await db.insert(networks).values([
    {
      name: "LAN Principal",
      cidr: "192.168.1.0/24",
      gateway: "192.168.1.1",
      vlan: 1,
      description: "Réseau local principal - bureaux",
      isActive: true,
    },
    {
      name: "DMZ",
      cidr: "10.0.0.0/24",
      gateway: "10.0.0.1",
      vlan: 10,
      description: "Zone démilitarisée - serveurs publics",
      isActive: true,
    },
    {
      name: "Wi-Fi Invités",
      cidr: "192.168.10.0/24",
      gateway: "192.168.10.1",
      vlan: 20,
      description: "Réseau Wi-Fi pour visiteurs",
      isActive: true,
    },
  ]).$returningId();

  // Create demo devices - LAN Principal
  const [router, coreSwitch, server1, server2, workstation1, workstation2, printer, ap1, firewall] = await db
    .insert(devices)
    .values([
      {
        ipAddress: "192.168.1.1",
        macAddress: "00:1A:2B:3C:4D:5E",
        hostname: "router-core",
        deviceType: "router",
        vendor: "Cisco",
        os: "IOS",
        osVersion: "15.7",
        status: "online",
        lastSeen: new Date(),
        firstSeen: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
        responseTime: 2,
        openPorts: [22, 80, 443, 161],
        networkId: network1.id,
        x: 400,
        y: 100,
        description: "Routeur principal - Gateway Internet",
      },
      {
        ipAddress: "192.168.1.2",
        macAddress: "00:1A:2B:3C:4D:5F",
        hostname: "switch-core",
        deviceType: "switch",
        vendor: "Cisco",
        os: "IOS-XE",
        osVersion: "16.12",
        status: "online",
        lastSeen: new Date(),
        firstSeen: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
        responseTime: 1,
        openPorts: [22, 443, 161],
        networkId: network1.id,
        parentId: 1,
        x: 400,
        y: 250,
        description: "Switch core - 48 ports Gigabit",
      },
      {
        ipAddress: "192.168.1.10",
        macAddress: "00:1A:2B:3C:4D:60",
        hostname: "srv-web-01",
        deviceType: "server",
        vendor: "Dell",
        os: "Ubuntu",
        osVersion: "22.04 LTS",
        status: "online",
        lastSeen: new Date(),
        firstSeen: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000),
        responseTime: 5,
        openPorts: [22, 80, 443, 3306],
        networkId: network1.id,
        parentId: 2,
        x: 200,
        y: 400,
        description: "Serveur Web principal",
      },
      {
        ipAddress: "192.168.1.11",
        macAddress: "00:1A:2B:3C:4D:61",
        hostname: "srv-db-01",
        deviceType: "server",
        vendor: "Dell",
        os: "Ubuntu",
        osVersion: "22.04 LTS",
        status: "online",
        lastSeen: new Date(),
        firstSeen: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000),
        responseTime: 8,
        openPorts: [22, 3306, 5432],
        networkId: network1.id,
        parentId: 2,
        x: 600,
        y: 400,
        description: "Serveur Base de données",
      },
      {
        ipAddress: "192.168.1.50",
        macAddress: "00:1A:2B:3C:4D:62",
        hostname: "pc-admin",
        deviceType: "workstation",
        vendor: "HP",
        os: "Windows 11",
        osVersion: "23H2",
        status: "online",
        lastSeen: new Date(),
        firstSeen: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000),
        responseTime: 12,
        openPorts: [445, 3389],
        networkId: network1.id,
        parentId: 2,
        x: 100,
        y: 550,
        description: "Poste de travail Administrateur",
      },
      {
        ipAddress: "192.168.1.51",
        macAddress: "00:1A:2B:3C:4D:63",
        hostname: "pc-dev-01",
        deviceType: "workstation",
        vendor: "Lenovo",
        os: "Windows 11",
        osVersion: "23H2",
        status: "offline",
        lastSeen: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
        firstSeen: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000),
        responseTime: null,
        openPorts: [445, 3389],
        networkId: network1.id,
        parentId: 2,
        x: 300,
        y: 550,
        description: "Poste développeur",
      },
      {
        ipAddress: "192.168.1.100",
        macAddress: "00:1A:2B:3C:4D:64",
        hostname: "printer-hall",
        deviceType: "printer",
        vendor: "HP",
        os: "Embedded",
        osVersion: "2.1",
        status: "warning",
        lastSeen: new Date(),
        firstSeen: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000),
        responseTime: 45,
        openPorts: [80, 9100],
        networkId: network1.id,
        parentId: 2,
        x: 500,
        y: 550,
        description: "Imprimante multifonction hall",
      },
      {
        ipAddress: "192.168.1.5",
        macAddress: "00:1A:2B:3C:4D:65",
        hostname: "ap-etage1",
        deviceType: "access_point",
        vendor: "Ubiquiti",
        os: "UniFi",
        osVersion: "6.5",
        status: "online",
        lastSeen: new Date(),
        firstSeen: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
        responseTime: 3,
        openPorts: [22, 443, 8080],
        networkId: network1.id,
        parentId: 2,
        x: 700,
        y: 550,
        description: "Point d'accès Wi-Fi Étage 1",
      },
      {
        ipAddress: "10.0.0.1",
        macAddress: "00:1A:2B:3C:4D:66",
        hostname: "fw-perimeter",
        deviceType: "firewall",
        vendor: "Palo Alto",
        os: "PAN-OS",
        osVersion: "10.2",
        status: "online",
        lastSeen: new Date(),
        firstSeen: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
        responseTime: 2,
        openPorts: [22, 443],
        networkId: network2.id,
        x: 800,
        y: 100,
        description: "Firewall périmètre",
      },
    ]).$returningId();

  // Create connections
  await db.insert(deviceConnections).values([
    { sourceId: 1, targetId: 2, connectionType: "ethernet", bandwidth: "10 Gbps", latency: 1, status: "active" },
    { sourceId: 2, targetId: 3, connectionType: "ethernet", bandwidth: "1 Gbps", latency: 2, status: "active" },
    { sourceId: 2, targetId: 4, connectionType: "ethernet", bandwidth: "1 Gbps", latency: 2, status: "active" },
    { sourceId: 2, targetId: 5, connectionType: "ethernet", bandwidth: "1 Gbps", latency: 3, status: "active" },
    { sourceId: 2, targetId: 6, connectionType: "ethernet", bandwidth: "1 Gbps", latency: 3, status: "inactive" },
    { sourceId: 2, targetId: 7, connectionType: "ethernet", bandwidth: "100 Mbps", latency: 5, status: "active" },
    { sourceId: 2, targetId: 8, connectionType: "ethernet", bandwidth: "1 Gbps", latency: 2, status: "active" },
    { sourceId: 1, targetId: 9, connectionType: "fiber", bandwidth: "10 Gbps", latency: 1, status: "active" },
    { sourceId: 3, targetId: 4, connectionType: "ethernet", bandwidth: "1 Gbps", latency: 1, status: "active" },
  ]);

  // Create device configs
  await db.insert(deviceConfigs).values([
    { deviceId: 1, configKey: "snmp.community", configValue: "public", configType: "string", category: "SNMP", description: "Communauté SNMP lecture seule" },
    { deviceId: 1, configKey: "dhcp.enabled", configValue: "true", configType: "boolean", category: "DHCP", description: "Activer le serveur DHCP" },
    { deviceId: 1, configKey: "dhcp.range_start", configValue: "192.168.1.100", configType: "string", category: "DHCP", description: "Début plage DHCP" },
    { deviceId: 1, configKey: "dhcp.range_end", configValue: "192.168.1.200", configType: "string", category: "DHCP", description: "Fin plage DHCP" },
    { deviceId: 1, configKey: "nat.enabled", configValue: "true", configType: "boolean", category: "NAT", description: "NAT activé" },
    { deviceId: 2, configKey: "vlan.1", configValue: "192.168.1.0/24", configType: "string", category: "VLAN", description: "VLAN Management" },
    { deviceId: 2, configKey: "vlan.10", configValue: "10.0.0.0/24", configType: "string", category: "VLAN", description: "VLAN DMZ" },
    { deviceId: 2, configKey: "spanning_tree", configValue: "rstp", configType: "string", category: "Switching", description: "Mode Spanning Tree" },
    { deviceId: 3, configKey: "nginx.worker_processes", configValue: "auto", configType: "string", category: "Web", description: "Workers Nginx" },
    { deviceId: 3, configKey: "php.max_execution_time", configValue: "30", configType: "number", category: "PHP", description: "Temps max d'exécution PHP" },
    { deviceId: 3, configKey: "mysql.max_connections", configValue: "151", configType: "number", category: "Database", description: "Connexions MySQL max" },
    { deviceId: 4, configKey: "postgresql.shared_buffers", configValue: "256MB", configType: "string", category: "Database", description: "Buffers partagés PostgreSQL" },
    { deviceId: 4, configKey: "backup.schedule", configValue: "0 2 * * *", configType: "string", category: "Backup", description: "Planification sauvegarde" },
    { deviceId: 5, configKey: "domain.joined", configValue: "corp.local", configType: "string", category: "AD", description: "Domaine Active Directory" },
    { deviceId: 8, configKey: "wifi.ssid", configValue: "Corp-WiFi", configType: "string", category: "WiFi", description: "SSID Wi-Fi" },
    { deviceId: 8, configKey: "wifi.security", configValue: "WPA3-Enterprise", configType: "string", category: "WiFi", description: "Sécurité Wi-Fi" },
    { deviceId: 8, configKey: "wifi.channel", configValue: "6", configType: "number", category: "WiFi", description: "Canal 2.4GHz" },
    { deviceId: 9, configKey: "rules.inbound", configValue: "[{\"port\":443,\"action\":\"allow\"},{\"port\":22,\"action\":\"allow\"}]", configType: "json", category: "Firewall", description: "Règles entrantes" },
    { deviceId: 9, configKey: "ids.enabled", configValue: "true", configType: "boolean", category: "Security", description: "Détection d'intrusion" },
  ]);

  // Create scan jobs
  await db.insert(scanJobs).values([
    {
      name: "Scan initial",
      networkId: network1.id,
      status: "completed",
      scanType: "full",
      totalHosts: 254,
      scannedHosts: 254,
      foundDevices: 8,
      startTime: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
      endTime: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000 + 15 * 60 * 1000),
    },
    {
      name: "Scan rapide DMZ",
      networkId: network2.id,
      status: "completed",
      scanType: "quick",
      totalHosts: 24,
      scannedHosts: 24,
      foundDevices: 1,
      startTime: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
      endTime: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000 + 2 * 60 * 1000),
    },
    {
      name: "Scan quotidien",
      networkId: network1.id,
      status: "running",
      scanType: "quick",
      totalHosts: 254,
      scannedHosts: 120,
      foundDevices: 6,
      startTime: new Date(),
    },
  ]);

  console.log("Seed completed successfully!");
}

seed().catch(console.error);
